### ISSUE TITLE
what is the size needed for LQ-Nets vgg model to run

### ISSUE THREAD

**Issue by monkeyking** [Microsoft/LQ-Nets#12]
When I tried to run the VGG model ,I see the RAM quickly ran out and LQ-Nets be killed by system.
I am not sure my ram is enough for the Net to run.

**Comment by monkeyking** [comment]
system : ubuntu 18
ram : 16GB
gpu : 1080TI

**Comment by EowinYe** [comment]
How much is the ram in 1080TI? I ran it on M40 with 24G before. Since VGG needs very large memories, you can try to decrease the batch size if you'd like to run it on 1080TI (Also decrease the learning rate).
