### ISSUE TITLE
resnet20 architecture

### ISSUE THREAD

**Issue by blueardour** [Microsoft/LQ-Nets#14]
Hi, 

Thanks for sharing the code. I noticed that the resnet20 was employed in the CIFAR10 quantization. However, I didn't find the architecture. I ever saw two versions of resnet20.  One is for small dataset such as CIFAR, another is for bigger dataset, such as imagenet. The difference is the width of the channel count. I wonder if it is possible for you to share detail definition of resnet20? Thanks

**Comment by EowinYe** [comment]
Hi,
we did not release the architecture code for resnet-cifar. You can check [tensorflow models](https://github.com/tensorflow/models/tree/master/research/resnet) or [tensorpack resnet](https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet) for references. You could simply modify the network architecture by replace the conv2d op with our conv2dquant op.

**Comment by blueardour** [comment]
ok, thanks very much
