### ISSUE TITLE
loss=0

### ISSUE THREAD

**Issue by shz1314** [Microsoft/LQ-Nets#16]
Hello,
  When i use your method, the value of classify loss sometimes is 0.0000.  Why? Does it cause by quantization?

**Comment by shz1314** [comment]
I cannot stand your code in learned_quatization line 58(ctx = get_current_tower_context()) and line 82 (        if ctx.is_main_training_tower:)  ,so i change the line 82 into (if 1)

**Comment by EowinYe** [comment]
It's possible when you train the model in the CIFAR10 dataset and get 0 loss. The second one is multi-GPU training setting on Tensorpack. For more details, please check the official Tensorpack repo.

**Comment by shz1314** [comment]
Very thanks for your reply, so can i change it (if 1)? I just use 1 gpu.




------------------ 原始邮件 ------------------
发件人: "Yijun Li"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 上午9:35
收件人: "microsoft/LQ-Nets"<LQ-Nets@noreply.github.com>;
抄送: "Orange"<981449149@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/LQ-Nets] loss=0 (#16)




It's possible when you train the model in the CIFAR10 dataset and get 0 loss. This second one is multi-GPU training setting on Tensorpack. For more details, please check the official Tensorpack repo.

**Comment by EowinYe** [comment]
If you just use 1 GPU, I think it would work.
