### ISSUE TITLE
Lower quantized values set to 0 instead of levels[0]

### ISSUE THREAD

**Issue by Guriido** [Microsoft/LQ-Nets#5]
https://github.com/Microsoft/LQ-Nets/blob/ca764ae6a5ba9de0627aee2e7fe68c9cf3875305/learned_quantization.py#L77-L79

It seems to me that for real input values below than `thrs[0]`, that are those in (*t<sub>1</sub>, t<sub>2</sub>*] in paper notations, the corresponding y values are set to `0` instead of  `levels[0]` (i.e. *q<sub>1</sub>* in paper).

Am I overlooking something ?

**Comment by Guriido** [comment]
and this remark seems to apply as well to `bits_y`, it is initialized to bit strings of zeros, which may not be the level_code corresponding to the minimal value (`levels[0]` after sorting), and should be initially set to something like `zero_bits_y + level_codes[sort_id[0][0]]` 
https://github.com/Microsoft/LQ-Nets/blob/ca764ae6a5ba9de0627aee2e7fe68c9cf3875305/learned_quantization.py#L74

**Comment by zhuangbohan** [comment]
If weights are set to {-1, +1} and activations are set to {0, 1} , then it cannot use simple XNOR operations to replace convolution. What's more, the representability becomes much stronger because this is ternary operation!! The output should be {-1, 0, 1} rather than {-1, 1}. Actually, it will influence the results a lot.

**Comment by EowinYe** [comment]
@Guriido 
In the activation quantization function, levels[0] is always zero and level_codes[0] is bit strings of zeros too. 
Maybe our code style makes you confused.

**Comment by Guriido** [comment]
@EowinYe 
Thank you for your answer
I was confused with the paper which sets *q<sub>1</sub>* to potentially non-zero values (but it was the default setting for weights, and encoding activations with {0, 1} gives obviously *q<sub>1</sub>*=0 )

Thank you for the clarification !

@zhuangbohan This may be discussed with another issue, as it is not directly related to the problem I thought I found. Thus, I close this issue
